<cite>Darryl Oatridge, August 2022<cite>

In [1]:
import os

In [2]:
os.environ['HADRON_PM_PATH'] = '../0_hello_meta/demo/contracts'
os.environ['HADRON_DEFAULT_PATH'] = '../0_hello_meta/demo/data'

## Feature Engineering

In [3]:
from ds_discovery import Wrangle, Transition

In [4]:
# get the instance
wr = Wrangle.from_env('hello_wr', has_contract=False)

In [5]:
source = Transition.from_env('hello_tr').get_persist_contract()
wr.set_source_contract(source)
wr.set_persist()

In [6]:
df = wr.load_source_canonical()

In [7]:
wr.canonical_report(df)

In [8]:
df['family'] = wr.tools.correlate_aggregate(df, headers=['parch', 'sibsp'], agg='sum', column_name='family')

In [9]:
df['deck'] = wr.tools.correlate_custom(df, code_str="@['cabin'].str[0]", column_name='deck')

In [10]:
selection = [wr.tools.select2dict(column='family', condition='@==0')]
df['is_alone'] = wr.tools.correlate_selection(df, selection=selection, action=1, default_action=0, column_name='is_alone')

In [11]:
df = wr.tools.model_to_category(df, headers=['family','deck','is_alone'], intent_order=1, column_name='to_category')

In [12]:
wr.report_intent()

## Component Pipeline

In [13]:
wr.run_component_pipeline()

In [14]:
wr.canonical_report(df)